name: exch_client
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <exch_client dependencies>

  redis_client:
    git: https://github.com/patefacio/redis_client

  ebisu:
    git: https://github.com/patefacio/ebisu

# end <exch_client dependencies>

dev_dependencies:
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <exch_client dev dependencies>
# end <exch_client dev dependencies>

dependency_overrides:
# custom <exch_client dependency overrides>
# end <exch_client dependency overrides>

transformers:

# custom <exch_client transformers>
# end <exch_client transformers>

